spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: zzgwh
    password: Zzgwh#1234
    url: jdbc:mysql://192.168.0.88:3306/SpringCloud_Sell?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
  jpa:
    show-sql: true  
  rabbitmq:
    host: 192.168.0.88
    port: 5672
    username: guest
    password: guest
  redis:
  host: 192.168.0.88
  port: 6379
env:
  test
girl:
  name: lili
  age: 18
